### ISSUE TITLE
grad-civs fpsdrops auf dem server

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_MoneyInTheMist.Altis#14]

**Comment by nomisum** [comment]
making vanilla civ modules dynamic as a possible alternative could be a challenge.

other than that engima could provide a quick+dirty fix.

**Comment by McDiod** [comment]
I fixed the major issue with grad-civs, so updating should do. Might still have somewhat of an impact on performance, but not the hard stuttering that we had.

**Comment by nomisum** [comment]
update civs to latest release

**Comment by McDiod** [comment]
works
