### ISSUE TITLE
briefcase sinks into ground

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_MoneyInTheMist.Altis#17]
- [x] when dropping it due to taking up a firearm from inventory / dropping by action

`(missionNamespace getVariable ["mitm_briefcase",objNull]) setPos getPos player` is a workaround

**Comment by nomisum** [comment]
seems to happen randomly.. sometimes dropping works flawlessly

**Comment by nomisum** [comment]
maybe connected to this waitAndExecute async from setVariable... 
https://github.com/gruppe-adler/TvT_MoneyInTheMist.Altis/commit/69cd96fb3e37a8e1ddf43d15d3be51073404dacc#diff-a136fc1641be2e4a8f4deaff59c8600d

**Comment by McDiod** [comment]
still happening

**Comment by McDiod** [comment]
passiert immer noch, workaround mit admincommand geht aber
