### ISSUE TITLE
briefcase kills and knockouts players

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_MoneyInTheMist.Altis#21]

**Comment by McDiod** [comment]
possibly only when briefcase is dropped / attachedTo objects should not be able to collide with players

**Comment by AdlerXiviD** [comment]
Video of DerZade shows that it also happens when the briefcase is attached.

**Comment by nomisum** [comment]
https://community.bistudio.com/wiki/disableCollisionWith

Muss bei jeder Lokalitätsänderung ausgeführt werden. Dh bei jedem JIP bspw
