### ISSUE TITLE
Bugs 190909

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_MoneyInTheMist.Altis#29]
- [x] Fahrzeuge am Straßenrand teilweise ohne Fuel, teilweise mit sehr wenig
- [x] Fahrzeugschlüssel passen nicht zu Fahrzeugen der Seite
- [x] Reihenfolge der Spawnpunkte mischen? Opfor startet immer gegenüber von Kurier?
- [x] ~~AT Slots einbauen?~~
- [x] Replay
- [x] Spieler sind während des "Abspanns" noch bis zum Ende gemuted, da könnte man sie schon in den SpecChannel schieben
- [x] Koffer darf nicht im Fahrzeug weitergegeben werden
- [x] Funkreichweite erhöhen, weils nur Shortrange gibt
- [x] erster Admin Prompt für #mitm_accept wird immer noch nicht angezeigt

**Comment by nomisum** [comment]
out of screen rundenstart-counter auf 4k
![20190909200947_1](https://user-images.githubusercontent.com/500164/64563183-03bb6280-d34f-11e9-8eec-5197bf6304d4.jpg)

**Comment by McDiod** [comment]
Rundenstart Counter gibts im TvT-Template in 4K fähiger Version.

**Comment by nomisum** [comment]
Dass Kurier immer gegenüber Opfor startet stimmt nicht.

**Comment by nomisum** [comment]
@McDiod score nach dem replay?

**Comment by nomisum** [comment]
Ist AT wirklich nötig 🤔 ein Treffer und ein Team wäre hin.

**Comment by nomisum** [comment]
Die Teamstruktur müsste für größere Events auf Squad-Size geändert werden und mehr Slots hinzugefügt.

**Comment by nomisum** [comment]
glaube replay bräuchte ich hilfe beim einbauen.

**Comment by McDiod** [comment]
* score vor dem replay
* AT halte ich auch für unnötig. Anscheinend gabs ja mal welche (slotliste.xml), die wir dann ausgebaut haben.
