### ISSUE TITLE
increase tracking accuracy when briefcase in water

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_MoneyInTheMist.Altis#39]
https://github.com/gruppe-adler/TvT_MoneyInTheMist.Altis/blob/3844aad3927e8b83bf15545c7433c50f009d8944/functions/briefcase/fn_trackBriefcase.sqf#L27

**Comment by nomisum** [comment]
see https://github.com/gruppe-adler/TvT_MoneyInTheMist.Altis/pull/40

**Comment by McDiod** [comment]
I just tested the debris PR on Altis with choppy water. Debris was hard to see, so I think halving the accuracy is still necessary.

Edit: that would put it at 100m accuracy in water

**Comment by nomisum** [comment]
isnt the current radius already 50m?

trackingAccuracy = 250;                         // accuracy of tracking marker in m
trackingAccuracyFactorNoCarrier = 0.2;

and i agree waves wont work well with the flat garbage patch

**Comment by McDiod** [comment]
Right, i was looking at `trackingAccuracyFactorNoCourier`, nevermind then. For waves see changes I made in the PR.
