### ISSUE TITLE
Cheatermeldung bei Disconnect

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_MoneyInTheMist.Altis#4]

**Comment by nomisum** [comment]
currently there is only one disconnect EH dropping the briefcase.

is this meant to alert other players this has happened?

**Comment by McDiod** [comment]
This is what it's about:
https://github.com/gruppe-adler/TvT_MoneyInTheMist.Altis/blob/master/functions/setup/fn_enforceStartTimer.sqf

It's basically making sure no one moves too far away from spawn while the Courier is using his headstart. Apparently players move to [0,0,0] for a split second on disconnect.

**Comment by nomisum** [comment]
so ... lets check for [0,0,0] then :D 
https://github.com/gruppe-adler/TvT_MoneyInTheMist.Altis/commit/0d1f65f0bc2a2a7461edfda3d771978fcf3ed0fb#diff-86ada1cb383536b287417c3c8ea50724R15

**Comment by McDiod** [comment]
works
