### ISSUE TITLE
Letzter Kurier-Abgabepunkt längere Interaktionszeit

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_MoneyInTheMist.Altis#8]

**Comment by nomisum** [comment]
how do I detect which one is the last task. always 7 tasks? 

https://github.com/gruppe-adler/TvT_MoneyInTheMist.Altis/blob/master/functions/courierTasks/fn_checkCourierTasksComplete.sqf#L5

**Comment by McDiod** [comment]
Last task is created here:

https://github.com/gruppe-adler/TvT_MoneyInTheMist.Altis/blob/master/functions/courierTasks/fn_checkCourierTasksComplete.sqf#L25

Interaction time is apparently a trigger timer, so we can pass a parameter to `fn_createTaskObjects` telling it to use a higher value here:

https://github.com/gruppe-adler/TvT_MoneyInTheMist.Altis/blob/master/functions/courierTasks/fn_createTaskObjects.sqf#L35

**Comment by nomisum** [comment]
Done with https://github.com/gruppe-adler/TvT_MoneyInTheMist.Altis/commit/a5feaad448d8dcb503554f2e965674f64cc6ce2a

Interaction time of 120s for last one sufficient? @McDiod
